### ISSUE TITLE
`HTML::TreeBuilder::LibXML::Node::new` is incompatible with `HTML::Element::new`

### ISSUE THREAD

**Issue by nanto** [tokuhirom/HTML-TreeBuilder-LibXML#12]
While `HTML::TreeBuilder::LibXML::Node` says that it is "HTML::Element compatible API", `new` method is incompatible with [that of `HTML::Element`](https://metacpan.org/pod/HTML::Element#new). With `HTML::TreeBuilder::LibXML::Node`, we can't do operations such as:

```perl
my $new_element = ref($element)->new('div');
$element->replace_with($new_element);
```

**Comment by tokuhirom** [comment]
Thanks for your report. I improved compatibility.
