### ISSUE TITLE
Please release 0.27

### ISSUE THREAD

**Issue by davorg** [tokuhirom/HTML-TreeBuilder-LibXML#19]
I see that release 0.27 is [available on CPAN](https://metacpan.org/release/TOKUHIROM/HTML-TreeBuilder-LibXML-0.27/view/lib/HTML/TreeBuilder/LibXML.pm), but it's not indexed as the latest version (which is still [0,26 from 2016](https://metacpan.org/pod/HTML::TreeBuilder::LibXML)).

Given that 0.27 has [much better test results](http://matrix.cpantesters.org/?dist=HTML-TreeBuilder-LibXML+0.27) could you please do whatever needs to be done in order to tell CPAN that 0.27 exists?

**Comment by davorg** [comment]
Hi @tokuhirom, would you consider giving me (DAVECROSS) COMAINT permission on CPAN for HTML::TreeBuilder::LibXML so I can work on getting version 0.27 indexed properly?

**Comment by tokuhirom** [comment]
Sorry, I missed the notification. Sorry for the late response.
I added you as a collaborator on github. I also added you as a co-maint on PAUSE.
I don't currently have enough time to maintain this module, so please feel free to do the necessary maintenance.
![CleanShot 2024-06-20 at 09 00 37@2x](https://github.com/tokuhirom/HTML-TreeBuilder-LibXML/assets/21084/df4eaf3b-fd77-41b1-bf45-c13eeb42dc60)

**Comment by davorg** [comment]
That's great. Thanks.

**Comment by davorg** [comment]
It looks like it might have been a PAUSE glitch when you uploaded 0.27. I've just uploaded exactly the same code as 0.28 and it has worked without problems.

https://metacpan.org/pod/HTML::TreeBuilder::LibXML
